export const mockApplicationList = [
  {
    appID: "40f657a8-284c-4a9e-b8b8-78ad54d8ba4b",
    clientAppID: null,
    name: "B2B Webshop ",
    icon: null,
    briefDescription: "Web shop",
    longDescription: "Shop for B2B in Web",
    systemRequirements: "None",
    userGuides: "None",
    latestUpdates: "None",
    appLink: "https://b2bwebshop.siweb01.vm.aws.cloud.skanlog.com/",
    fileLink: "",
    isActive: true,
    isFavorite: true,
    isGranted: false,
  },
  {
    appID: "8e8f28a1-6791-4670-b526-3722f51b6b04",
    clientAppID: null,
    name: "Central",
    icon: null,
    briefDescription: "Skanlog Central",
    longDescription: null,
    systemRequirements: null,
    userGuides: null,
    latestUpdates: null,
    appLink: null,
    fileLink: null,
    isActive: true,
    isFavorite: false,
    isGranted: false,
  },
  {
    appID: "74d3183e-6a9c-4adf-b416-234ffc438ac8",
    clientAppID: null,
    name: "Event Capture",
    icon: null,
    briefDescription: "Capture for Event",
    longDescription: "The capture for the events in Skanlog",
    systemRequirements: "None",
    userGuides: "None",
    latestUpdates: "None",
    appLink: "",
    fileLink:
      "http://eventcapture.siweb01.vm.aws.cloud.skanlog.com/public/com.skanlog.event_capture.apk",
    isActive: true,
    isFavorite: true,
    isGranted: false,
  },
  {
    appID: "6f1cbb0a-dd21-4f40-8151-4c02a3d26a33",
    clientAppID: null,
    name: "Gateway",
    icon: null,
    briefDescription: "Store og Skanlog Apps",
    longDescription:
      "Store og Skanlog Apps Long Description\n\ndsadada\n\n\ndasdsad",
    systemRequirements: "",
    userGuides: "",
    latestUpdates: "",
    appLink: "appstore.test.skanlog.com",
    fileLink: "",
    isActive: true,
    isFavorite: true,
    isGranted: false,
  },
  {
    appID: "e043610c-c656-4616-9317-fbf7685a6687",
    clientAppID: null,
    name: "People Catalog",
    icon: null,
    briefDescription: "Catalog for people ",
    longDescription:
      "It is the catalog for the people\n\nUsed in creating roles\nUsed in creating sites",
    systemRequirements: "System Requirements for People Catalog",
    userGuides: "",
    latestUpdates: "",
    appLink: "https://peoplecatalog.siweb01.vm.aws.cloud.skanlog.com/",
    fileLink: "",
    isActive: true,
    isFavorite: false,
    isGranted: false,
  },
  {
    appID: "ee2cd6db-5a8b-443d-962b-b765baca9d34",
    clientAppID: null,
    name: "Skanlog BI",
    icon: null,
    briefDescription: "Skanlog BI",
    longDescription: "The BI for Skanlog",
    systemRequirements: "None",
    userGuides: "None",
    latestUpdates: "None",
    appLink: "https://powerbi.test.skanlog.com/",
    fileLink: "",
    isActive: true,
    isFavorite: false,
    isGranted: false,
  },
  {
    appID: "7c474847-6419-4779-a818-97b297fa238d",
    clientAppID: null,
    name: "Skanlog Biztalk Integration",
    icon: null,
    briefDescription: "Biztalk for Skanlog",
    longDescription: "The biztalk inegration for Skanlog",
    systemRequirements: "None",
    userGuides: "None",
    latestUpdates: "None",
    appLink: "",
    fileLink: "",
    isActive: true,
    isFavorite: false,
    isGranted: false,
  },
  {
    appID: "0876dc7a-f21f-47b8-84e1-b1777a40bcc6",
    clientAppID: null,
    name: "Skanlog Calendar",
    icon: null,
    briefDescription: "Calendar for skanlog",
    longDescription: "The very calendar for Skanlog people",
    systemRequirements: "is not none",
    userGuides: "is not none",
    latestUpdates: "none",
    appLink: "https://calendar.siweb01.vm.aws.cloud.skanlog.com/",
    fileLink: "",
    isActive: true,
    isFavorite: true,
    isGranted: false,
  },
  {
    appID: "867c8d68-736d-43c8-98c0-5c913fd8ad3b",
    clientAppID: null,
    name: "Skanlog Lopo",
    icon: null,
    briefDescription: "Lopo for Skanlog",
    longDescription: "The lopo for Skanlog peeps",
    systemRequirements: "None",
    userGuides: "None",
    latestUpdates: "None",
    appLink: "https://lopo.skanlog.com/",
    fileLink: "",
    isActive: true,
    isFavorite: false,
    isGranted: false,
  },
  {
    appID: "3d911d14-6b4c-4993-a9ac-b34cb97aae8f",
    clientAppID: null,
    name: "Skanlog Tower",
    icon: null,
    briefDescription: "Tower Skanlog",
    longDescription: "The very tower for skanlog",
    systemRequirements: "None",
    userGuides: "None",
    latestUpdates: "None",
    appLink: "",
    fileLink: "",
    isActive: true,
    isFavorite: true,
    isGranted: false,
  },
  {
    appID: "4232b1f4-85af-4bc9-b10d-a6abbcb6469e",
    clientAppID: null,
    name: "Skanlog Transport Plan",
    icon: null,
    briefDescription: "Transport plan in skanlog",
    longDescription: "The Skanlog's transport plan",
    systemRequirements: "None",
    userGuides: "None",
    latestUpdates: "None",
    appLink: "",
    fileLink: "",
    isActive: true,
    isFavorite: false,
    isGranted: false,
  },
  {
    appID: "ddba75ef-5f0a-4323-8c59-64ad6dd01243",
    clientAppID: null,
    name: "Sunflower",
    icon: null,
    briefDescription: "Skanlog Sunflower",
    longDescription: null,
    systemRequirements: null,
    userGuides: null,
    latestUpdates: null,
    appLink: null,
    fileLink: null,
    isActive: true,
    isFavorite: false,
    isGranted: false,
  },
  {
    appID: "2125e304-64bf-4b5d-9234-a39fe50e6cdd",
    clientAppID: null,
    name: "TimeTracker",
    icon: null,
    briefDescription: "Skanlog Time Tracker",
    longDescription: null,
    systemRequirements: null,
    userGuides: null,
    latestUpdates: null,
    appLink: null,
    fileLink: null,
    isActive: true,
    isFavorite: false,
    isGranted: false,
  },
  {
    appID: "b64fdf05-8cec-4022-839c-7f1320252aeb",
    clientAppID: null,
    name: "Visitor System",
    icon: null,
    briefDescription: "See visitor requests",
    longDescription: "See and create visitor requests",
    systemRequirements: "",
    userGuides: "",
    latestUpdates: "",
    appLink: "https://visitorsystem.siweb01.vm.aws.cloud.skanlog.com",
    fileLink: "",
    isActive: true,
    isFavorite: true,
    isGranted: true,
  },
];
